(use-package magit
  :bind (("C-c m g" . magit-status)
         ("C-c m s" . magit-stage-file)
         ("C-c m u" . magit-unstage-file)
         ("C-c m U" . magit-unstage-all)
         ("C-c m c" . magit-commit)
         ("C-c m b b" . magit-checkout)
         ("C-c m b c" . magit-branch-and-checkout)
         ("C-c m b l" . magit-branch)
         ("C-c m b r" . magit-branch-rename)
         ("C-c m b d" . magit-branch-delete)
         ("C-c m f" . magit-fetch-all)
         ("C-c m p p" . magit-push-current)
         ("C-c m p l" . magit-pull)
         ("C-c m t s" . magit-stash)
         ("C-c m t l" . magit-stash-list)
         ("C-c m t c" . magit-stash-clear)
         ("C-c m t p" . magit-stash-pop)
         ("C-c m t a" . magit-stash-apply)
         ("C-c m l l" . magit-log-current)
         ("C-c m l b" . magit-log-buffer-file)
         ("C-c m r r" . magit-reset)
         ("C-c m r h" . magit-reset-hard)
         ("C-c m d s" . magit-diff-staged)
         ("C-c m d u" . magit-diff-unstaged)))

(provide 'init-magit)
